name: Release

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build-artifacts:
    if: github.head_ref == 'release' && github.event.pull_request.merged == true
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    env:
      package_name: cli-template

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.target }}

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: Swatinem/rust-cache@v2.7.7
      - name: Install host target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Create Tar Archive (Unix)
        if: ${{ matrix.os != 'windows-latest' }}
        run: tar -czf cli-template-${{ matrix.target }}.tgz -C target/${{ matrix.target }}/release cli-template

      - name: Create Tar Archive (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: tar -czf cli-template-${{ matrix.target }}.tgz -C target/${{ matrix.target }}/release cli-template.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: ${{ matrix.target }}
          path: cli-template-${{ matrix.target }}.tgz
          if-no-files-found: error

  release:
    needs: [build-artifacts]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/download-artifact@v4.1.8
        with:
          path: artifacts
          merge-multiple: true
      - uses: knope-dev/action@v2.1.0
        with:
          version: 0.18.3
      - run: knope release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # publish-crate:
  #   needs: [release]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4.2.2
  #     - uses: Swatinem/rust-cache@v2.7.7
  #     - uses: katyo/publish-crates@v2
  #       with:
  #         registry-token: ${{ secrets.CARGO_TOKEN }}
